#!/bin/bash
#==============================================================================
#
# File:         bequiesce/beiquesce
# Language:     Bash
# Copyright:    Joe Honton © 2015
# License:      CC-BY-NC-ND 4.0
# Initial date: Sep 22, 2015
# Contents:     Bequiesce, Because 99.999 Doesn't Just Happen
#
# Example 1:    bash ../bequiesce/bequeisce test/cases/main.test.js
# Example 2:    bash ../bequiesce/bequeisce test/cases/test-cases.exim
#
#==============================================================================
if [ $# -lt 1 ]
then
  echo ""
  echo "Usage: bequiesce {testfile | testdir}"
  echo "   (only *.test.js files will be included if {testdir} is provided)"
  exit
fi

# where is this bash script?
THIS_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
echo $THIS_DIR

# execute
node --use_strict $THIS_DIR/../es5/bequiesce/src/main.js $1