#!/bin/bash
if [ $# -lt 1 ]
then
  echo "Usage: bequiese sourcefiles"
  exit
fi

# where is this bash script?
THIS_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
echo $THIS_DIR

# execute
node --use_strict $THIS_DIR/es5/main.js $1