#!/bin/bash
if [ $# -lt 1 ]
then
  echo ""
  echo "Usage: bequiesce {testfile | testdir}"
  echo "   (only *.test.js files will be included if {testdir} is provided)"
  exit
fi

# where is this bash script?
THIS_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
echo $THIS_DIR

# execute
node --use_strict $THIS_DIR/es5/main.js $1